### ISSUE TITLE
Update this eslint config to something we like, and standardize on it

### ISSUE THREAD

**Issue by calebeby** [cloudfour/eslint-config#1]
None of these repos are using this eslint config. They each have their own (different) eslint config:

- https://github.com/cloudfour/drizzle-builder/blob/master/.eslintrc
- https://github.com/cloudfour/core-gulp-tasks/blob/master/.eslintrc
- https://github.com/cloudfour/drizzle/blob/master/.eslintrc

I think we should change all the repos so they use this eslint config. We can update this eslint config if its rules don't match what we want.

Also: can we standardize on using [Prettier](https://prettier.io/) as a formatter?

cc: @tylersticka @gerardo-rodriguez

**Comment by tylersticka** [comment]
I've always relied on the dev team to tell me which config to use. 😅 

So I'll punt to @gerardo-rodriguez on this.

**Comment by gerardo-rodriguez** [comment]
It sure would be nice to have consistency. :)

> Also: can we standardize on using Prettier as a formatter?

I haven't dug into Prettier but have heard good things about it. I'm open to learning more and considering it as a tool to assist us as well. 😉
