### ISSUE TITLE
Capitalized comments, discussion

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/eslint-config#16]
I am _for_ having comments capitalized for consistency. We should be able to use basic grammar skills when writing comments.

_But_, I'm finding it a bit annoying when I am debugging and need to comment out a single line of code. In this scenario, the `capitalized-comments` ESLint rule kicks into play. Is there a way to configure this rule so that this does not happen? It very well may not be the case but I wanted to at least talk about it.

![screen shot 2018-12-07 at 3 55 01 pm](https://user-images.githubusercontent.com/459757/49678358-ac433b80-fa38-11e8-9fc7-9891953d239c.png)

🤔

**Comment by Josh68** [comment]
Partial non-sequitur: Why is it that I always realize I need to capitalize my Git commit messages when I get to the second sentence?

**Comment by calebeby** [comment]
I do not have a preference on whether comments are capitalized. [There is an `ignorePattern` option](https://eslint.org/docs/rules/capitalized-comments#ignorepattern), which is a regex string that is matched against the first word of the comment. It may be possible to configure this to ignore code. If that doesn't work, it may be possible to create a custom rule which ignores lines of code, with some sort of assumption that "code" is lines that match:

- Have a `.` followed by a not-whitespace
- End with a semicolon
- Have a non-whitespace followed by a `(`
- Have a `{` or `}` or `[` or `]`

**Comment by Josh68** [comment]
> I am _for_ having comments capitalized for consistency. We should be able to use basic grammar skills when writing comments.

Random hazard of this rule

`// someVar = someValue;`

I know we shouldn't be leaving commented code all over the place, but there may be cases when we want to, and don't want to break linting

**Comment by gerardo-rodriguez** [comment]
This feels like a non-issue now. I’m going to close it. 🙂
