### ISSUE TITLE
NPM script order affects linting output

### ISSUE THREAD

**Issue by Josh68** [cloudfour/eslint-config#19]
Docs show
```
"scripts": {
    "check-lint": "prettier --list-different '**/*.js' && eslint '**/*.js'",
    "lint": "prettier --write '**/*.js' && eslint --fix '**/*.js'"
  },
```
In some repos, we have `eslint` running before `prettier`. How this is setup dictates whether you see any output when just checking code (not running with `--fix`). It's nice to get feedback before fixing. Is there anything we should look at here, even just recommending running `eslint` before `prettier`?

**Comment by spaceninja** [comment]
I just dug into this, and want to recommend that we switch to using eslint-prettier, so that prettier runs as part of eslint, rather than a separate command. It works a treat on the LI repos.

**Comment by calebeby** [comment]
@spaceninja @Josh68 circling back to this issue, I think we can close it because I reversed the order of prettier and eslint in https://github.com/cloudfour/eslint-config/pull/88 (see #3 in that issue). Now eslint runs first, then prettier
