### ISSUE TITLE
Discuss no-unused-expressions rule with ternaries and short-circuit

### ISSUE THREAD

**Issue by calebeby** [cloudfour/eslint-config#7]
Discuss whether `&&` and ` ? : ` should be used in place of if/else, or if we should update the ESLint rule to disallow those

**Comment by gerardo-rodriguez** [comment]
I would like to make the argument that we try and make our code more _human_ readable regardless if being consumed by a dev or a designer. 

I'd rather we have `if` blocks over `&&`. I feel ternary `? :` statements are totally fine but I don't feel as comfortable with `? :` taking over `if`/`else` blocks. :)

**Comment by calebeby** [comment]
@josh68:

I think using ternaries where they are necessary and when the alternatives are verbose is fine:

```js
const foo = {
  name: 'asdf',
  port: something ? '1234' : '3000'
}
```

But in cases where an if/else can be easily used instead, I prefer that because it is more clear
