### ISSUE TITLE
Consider bundling plugins

### ISSUE THREAD

**Issue by calebeby** [cloudfour/eslint-config#8]
For https://github.com/calebeby/eslint-config, I discovered an approach for removing the need to [install all of the necessary plugins on each project](https://github.com/cloudfour/eslint-config#installation) by `require`ing the plugins' rules from the ESLint config, moving them under a namespace, and re-exporting them, forming a sort of super-plugin that exports all the rules from the other plugins, and a recommended config.

https://github.com/calebeby/eslint-config/blob/master/src/rules.js

I could use a similar approach here, which would make installing this ESLint config to other projects much easier. Also, this means that updating sub-plugins versions would mean updating them in this project, instead of trying to keep all the versions in sync across all Cloud Four projects.

@gerardo-rodriguez @Josh68

**Comment by gerardo-rodriguez** [comment]
This sounds like an excellent idea! 👏
