### ISSUE TITLE
Create prettier shared config on npm

### ISSUE THREAD

**Issue by calebeby** [cloudfour/eslint-config#80]
https://prettier.io/blog/2019/04/12/1.17.0.html#config

As of April 2019 prettier allows you to publish prettier configs to npm. That would be nice to version it so that if we update it, we can release a new version that the other repos can use.

It would be nice to include the prettier config in this repo since it is closely related with the eslint config

**Comment by spaceninja** [comment]
Closing this since we no longer do anything with Prettier in this repo, and our shared Prettier config is a single line.
